version: '3.7'
services:
    buildcontainer:
        container_name: ${Container_name}
        build:
            context: ./dockerfile
            dockerfile: ${dockerfile}
            args:
                - TZ=Asia/Istanbul
        environment:
            - repourl=https://github.com/marmarachain/marmara.git
            - branch=${branch}
            - build=${build}
        volumes:
         - ./volumes/${repolocation}/marmara/:/root/marmara
        entrypoint: bash -c "/root/build_MCL.sh"
