#!/bin/bash

# Check if argument is provided
if [ -z "$1" ]; then
    echo "You should use it like: update_nodes <ticker> or update_nodes all"
    echo "Example ./update_node mcl_node1"
    exit 1
fi

# If 'all' is provided, update all nodes
if [ "$1" == "all" ]; then
    echo "Updating all nodes..."
    docker-compose up -d --build
else
    # If specific ticker is provided, update the node for that ticker
    echo "Updating node for ticker: $1..."
    docker-compose up -d --build "$1"
fi
