FROM ubuntu:20.04
USER root
RUN apt-get update && apt-get upgrade -y
ARG TZ
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python3-zmq zlib1g-dev wget curl bsdmainutils automake cmake clang ntp ntpdate nano -y
WORKDIR /root
COPY build_MCL.sh .
RUN chmod +x /root/build_MCL.sh

